version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: reverseproxy
    ports:
     - 80:80
    privileged: True
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
    networks:
     - servicesnet
networks:
  servicesnet:
    external: true
